spring.application.name=agendamento-api

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ximed_db
spring.datasource.username=postgres
spring.datasource.password=wwxx13N
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mailtrap / SMTP config (Fictício apenas para inicializar o JavaMailSender)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=test
spring.mail.password=test
